### ISSUE TITLE
Information is blank after injecting a deb file into an ipa 

### ISSUE THREAD

**Issue by heinekenpsx** [Al4ise/Azule#116] opened 2022-09-06 06:00 UTC
I have to unzip this ipa file and repack it, otherwise Filza will crash when I click install
xXx:~/Downloads root# azule -i iMemScanTS.ipa -f
 H5GGv79.deb -o . -j
[*] Extracting H5GGv79.deb...
[*] Extracted H5GGv79.deb
[*] ID Successful
[*] Injected H5GG.dylib
[*] Generating iPA...
[*] Generated IPA at /var/mobile/Downloads/iMemScanTS+H5GGv79.deb.ipa
v0.7.3 :)
https://ibb.co/1KY4v72

**Comment by Al4ise** [comment] 2022-09-13 10:36
couldn't reproduce. what jailbreak are you running? and could you please run zip -T on the ipa file and tell me what it gives you? thank you

**Comment by heinekenpsx** [comment] 2022-09-13 14:05
I am using unc0ver
xXx:~/Downloads root# zip -T MemScanTS+H5GGv7.9.
deb.ipa 
test of MemScanTS+H5GGv7.9.deb.ipa OK

**Comment by Al4ise** [comment] 2022-09-13 14:20
hm, that's odd. could you send me the ipa and the deb?

**Comment by heinekenpsx** [comment] 2022-09-13 18:14
Yeah
https://drive.google.com/file/d/16mcREmIY_w4T6gTUSKtVlpwnQ1MO8V-N/view?usp=drivesdk

https://raw.githubusercontent.com/H5GG/H5GG/main/packages/H5GGv7.9%E9%80%9A%E7%94%A8%E6%B3%A8%E5%85%A5%E7%89%88.deb

**Comment by heinekenpsx** [comment] 2022-09-13 18:21
Ahh, I remembered, the same error occurs when I download the ipa file with ipatool, so i guess this error is related to ipatool

**Comment by Al4ise** [comment] 2022-11-05 14:29
i'm fairly certain it's not an issue with azule

**Comment by kingknuts** [comment] 2022-11-19 15:24
Hi, you are creating the IPA with the user root, so the output IPA have incorrect permissions (group wheel and user root), you must change them to the user and group mobile using filza for example. You don't have this issue if you create it without using the root user.

**Comment by Al4ise** [comment] 2022-12-27 13:22
> Hi, you are creating the IPA with the user root, so the output IPA have incorrect permissions (group "wheel" and user "root"), you must change them to the user and group "mobile" using filza for example. You don't have this issue if you create it without using the root user.

probably yeah, closing for now

**Closed by Al4ise** 2022-12-27 13:22 UTC
